id: P5A50EB3B
initial_creation_type: input
source_metadata:
  title: Dzogchen Series
  language: es
  description: 'The following texts are available as part of our Dzogchen (rdzogs
    chen) or Great Perfection series:'
  volume:
    c1cd60c10a514da1b1c73fc104bd61bd:
      title: Advice for Hor Özer
      parent: Advice
    d677f0a0b2c64afc960ca29999c78ffc:
      title: Advice for Palseng
      parent: Advice
    2bf6f0dc090b47eaab31ed883e0ccdfe:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      parent: Advice
    24778e82ba734dad80ba365370c5d16c:
      title: Advice for Garje Khamtrul Rinpoche
      parent: Advice
    b8730bfc41cf4d0a94dc8d2071b5a53a:
      title: Advice on Recognizing the Nature of Mind
      parent: Advice
    b72a8d169c22496c8c01ecf32b4a33dc:
      title: 'Advice: Emptying the Three Realms of Existence'
      parent: Advice
    a50db924452040feb9785a13d1b5f280:
      title: An Instruction on the Great Perfection
      parent: Advice
    7a9b667a60e64f5d899a0b59a20b9246:
      title: Brief Dzogchen Instruction
      parent: Advice
    a0f084ed0603460faba52bd0d63f3ad3:
      title: Direct Instruction
      parent: Advice
    5a3bcab3d4f34b56ba4a888cff93a1ac:
      title: Summary of the Key Points of Advice on Trekchö
      parent: Advice
    02510805ffc747c7bfb3ebd04396e15b:
      title: Vajra Verses on the Natural State
      parent: Advice
    dc6b139e691147ffb855ab3eea2c5e02:
      title: Advice for a King
      parent: Advice
    121ed10250374a5fbdb5dbe7121fd134:
      title: A Song of Advice for Gok Zangden
      parent: Advice
    5ca87ee593cc4f9b92c28ce97f29b8b5:
      title: A Song to Introduce the Unmistaken View of the Great Perfection
      parent: Advice
    9e7ef69129ad44ea97d2db974f8dadd4:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Advice
    80c3ab3fc0004528842959aaf1c11346:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Advice
    375821883d524056926b5fdfcacad3a3:
      title: 'Vomiting Gold: A Pith Instruction in the Form of Advice for the Diligent
        Practitioner, the Excellent Atsang'
      parent: Advice
    dcdb0a27ebde4e8cbebef023219be2d0:
      title: A Liberating Reminder
      parent: Advice
    0821e3b0a4454cd1937010fe92e72145:
      title: 'A Mirror Revealing the Crucial Points: Advice on the Ultimate Meaning'
      parent: Advice
    76c815e6b5ed4d6f965a0df055d0b498:
      title: 'A Wish-Fulfilling Gem: Guidance on the Meaning of Being at Ease with
        Illusion, A Dzogchen Teaching'
      parent: Advice
    205a9d26323a436eaa1f9ca2e9a5b913:
      title: 'From ''Finding Comfort and Ease in Meditation'': A Guide to Locations
        for Cultivating Samadhi'
      parent: Advice
    54eacbb9ebf147bbab5167a9c02513fb:
      title: 'From ''Finding Comfort and Ease in Meditation'': The Practitioner of
        Meditation'
      parent: Advice
    70f4f2f1b44a41f5b15ac488569c7bf9:
      title: 'A Lamp to Dispel Darkness: An Instruction that Points Directly to the
        Very Essence of Mind in the Tradition of ‘the Old Realized Ones’'
      parent: Advice
    22c36eea40de46e68d24455140636ef5:
      title: Pith Instruction on the Three Crucial Statements
      parent: Advice
    f730735bf6944b669a5fcfd64901ddd9:
      title: The Essence of Mind
      parent: Advice
    49ab990515c5499893b48f5c74474187:
      title: 'The Essence of Wisdom: How to Sustain the Face of Rigpa'
      parent: Advice
    4882650bde0c4c5baff0fa05beafae99:
      title: The Key Points of Trekchö
      parent: Advice
    5db99995a67743d7a70e101a9937d2b3:
      title: The Nature of Mind
      parent: Advice
    e4a061a87f854ac0bc16b0a1a01b6128:
      title: Advice on the View, Meditation, Action and Fruition
      parent: Advice
    11515cc58fbe4e6ca7e1eaf51c40ba3a:
      title: The Pointing-the-Staff Instruction
      parent: Advice
    87b18b2974a2485385b6107ce99f013f:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Advice
    3aebe244c4ba451992427b08273a1d2e:
      title: Principles of the Dzogchen Practice of Khordé Rushen
      parent: Advice
    53b956e29ac84dac8561626a8902a0d1:
      title: The Five Wisdoms
      parent: Advice
    b8c87c729fcf40848e3bc025412bc8e3:
      title: Advice on How to Put the Meaning of the Natural Great Perfection into
        Practice
      parent: Advice
    a541e9436be8486e8354d842e07aa9ae:
      title: 'Self-Liberating Meditation: A Profound Method for Attaining Enlightenment
        according to the Ultimate Great Perfection'
      parent: Advice
    07a3b91c5bf24fa68f35f4025b7a6c35:
      title: Advice from the Lips of Tertön Sogyal
      parent: Advice
    d68d98bc44de4a8fb03d05c94cb94f5d:
      title: A Torch to Illuminate Crucial Points of the Path of Meditation
      parent: Advice
    3cad7c4ae0bd4961b993020d3fe6dccb:
      title: The Four Uncommon Samayas of the Great Perfection
      parent: Advice
    38a99143c921455a960b59411f3053ef:
      title: A Brief Presentation of View, Meditation and Action
      parent: Advice
    9afe5501946d4a3f9bbb16653573977a:
      title: From the Oral Tradition of the Lama of Nyarong
      parent: Advice
    b614f205fadf4963896debf250823d05:
      title: On the Final Words of Orgyen Tendzin Norbu
      parent: Commentaries
    a00f8da901f9498aa899b0b4aac15504:
      title: 'The Precious Jewelled Key: A Synopsis of the Aspiration of the Great
        Perfection Mañjuśrī'
      parent: Commentaries
    b4e268716d1a4e0995af57940b8d8436:
      title: 'The Prayer of the Ground, Path & Fruition from the Heart-Essence of
        the Vast Expanse:'
      parent: Commentaries
    6db5a1f998094c21845c9064340fda89:
      title: Commentary on Vajra Verses on the Natural State
      parent: Commentaries
    0df47f5e551f4af68e1fd7be993555d4:
      title: Prayer to the Gurus of the Dzogchen Lineage
      parent: Lineage Prayers
    b8b595f90af9424cb0ae254ebab1b6f1:
      title: A Prayer to Shower Down the Rain of Wisdom
      parent: Lineage Prayers
    5072772e34b34dbb8702c63f5838c5da:
      title: How to Count the Four Permutations of Actual and Basis
      parent: Notes
    da0adaab22314f3ea39a5f68bef38dfb:
      title: Commentary on Some Terms from the Great Perfection
      parent: Notes
    61f9f3eeaeec4be7947a615270ac9c65:
      title: Brief Explanation of Clarification and Transcendental Resolution from
        the Oral Tradition of Nyala Sogyal
      parent: Notes
    d150388565e442a6981db54d571db009:
      title: How Liberation and Delusion Develop Out of the Clear Light of the Ground,
        etc.
      parent: Notes
    475895098f774fcf8cd3a1fd75615bb3:
      title: Notes from the Oral Tradition on Ālaya, Ālaya Consciousness, etc.
      parent: Notes
    13681aa1238a42d3aea399faab5429f0:
      title: Dzogchen Aspiration Prayer
      parent: Prayers
    56a4477853b0436d9bc259ada80909e6:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Prayers
    baafeefc330c4d9193fafacf15f08159:
      title: A Dzogchen Tögal Prayer
      parent: Prayers
    599fc9e50491491399ce19defeea9082:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Prayers
    2422f3c919f14460af9dcaa49302f467:
      title: 'The Pure Three Kāyas Ablaze in Perfect Splendour: A Prayer Based on
        the Meaning of the Great Perfection'
      parent: Prayers
    1d451866f8994584a0ff9b9230b032b9:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Prayers
    b20a10168d754c98a61aefe0014dd8d8:
      title: Prayer to Nyala Pema Dündul
      parent: Prayers
    83606310cd7440f486d6fcf426a64a3a:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Prayers
    470e32672576441fb3fa29ea73ac0c45:
      title: The Song of the Vajra
      parent: Songs
    03daabf15c7f498d9c22d2c6b389e503:
      title: A Song in Six Verses
      parent: Songs
    25a6a6f7833643fb92d8fe56e80d3d0e:
      title: Song of Experiential Certainty
      parent: Songs
    8a7f352eb89542db8069fd83692dcaf0:
      title: Spontaneously Written Song of Experience
      parent: Songs
    17f9bbc7efe54b7b899d1f51c542098d:
      title: In This Pure Awareness
      parent: Songs
    516d3b34742b4f8087972fe8a87cff8e:
      title: 'Aho Ye: Impressions of an Insightful Experience'
      parent: Songs
    5a6ca8595c6c46af9301d78e9c989bb4:
      title: Five-Verse Doha of Yogic Realization
      parent: Songs
    084cd7c1f66c44b1bfdf5958330cd1e4:
      title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin
        Nyima
      parent: Testament
created_at: '2022-03-01T03:36:31.992162'
last_modified_at: '2022-03-01T03:36:31.992165'
